#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
ISSUES_DIR="$ROOT_DIR/context/issues"
WIKI_DIR="$ROOT_DIR/context/wiki"
GH_BIN="${GH_BIN:-gh}"

command -v "$GH_BIN" >/dev/null 2>&1 || {
  echo "GitHub CLI not found. Set GH_BIN or add gh to PATH." >&2
  exit 1
}
command -v jq >/dev/null 2>&1 || {
  echo "jq is required to render issue Markdown files." >&2
  exit 1
}

REPOSITORY="$($GH_BIN repo view --json nameWithOwner --jq .nameWithOwner)"
mkdir -p "$ISSUES_DIR" "$WIKI_DIR"

echo "Exporting issues from $REPOSITORY..."
$GH_BIN issue list \
  --repo "$REPOSITORY" \
  --state all \
  --limit 100000 \
  --json number,title,body,state,stateReason,author,assignees,labels,milestone,createdAt,updatedAt,closedAt,url,comments \
  > "$ISSUES_DIR/issues.json"

jq -r '.[] | .number' "$ISSUES_DIR/issues.json" | while IFS= read -r number; do
  jq -r --argjson number "$number" '
    .[] | select(.number == $number) |
    "---\n" +
    "number: " + (.number | tostring) + "\n" +
    "state: " + .state + "\n" +
    "state_reason: " + (.stateReason // "") + "\n" +
    "author: " + (.author.login // "") + "\n" +
    "created_at: " + .createdAt + "\n" +
    "updated_at: " + .updatedAt + "\n" +
    "closed_at: " + (.closedAt // "") + "\n" +
    "url: " + .url + "\n" +
    "labels: [" + ([.labels[].name] | join(", ")) + "]\n" +
    "assignees: [" + ([.assignees[].login] | join(", ")) + "]\n" +
    "milestone: " + (.milestone.title // "") + "\n" +
    "---\n\n" +
    "# #" + (.number | tostring) + " — " + .title + "\n\n" +
    (.body // "") +
    (if (.comments | length) == 0 then "" else
      "\n\n## Comments\n" +
      ([.comments[] |
        "\n### " + (.author.login // "unknown") + " — " + .createdAt + "\n\n" +
        (.body // "")
      ] | join("\n"))
    end) + "\n"
  ' "$ISSUES_DIR/issues.json" > "$ISSUES_DIR/issue-$number.md"
done

cat > "$ISSUES_DIR/README.md" <<EOF
# GitHub issues mirror

Repository: https://github.com/$REPOSITORY

This directory is generated by \`scripts/sync-github-context.sh\`.
Create and edit issues on GitHub, then run the script to refresh this mirror.
\`issues.json\` is the machine-readable snapshot; \`issue-N.md\` files are the readable copies.
EOF

echo "Exporting wiki from $REPOSITORY..."
WIKI_TMP="$(mktemp -d)"
trap 'rm -rf "$WIKI_TMP"' EXIT

if git clone --quiet "https://github.com/$REPOSITORY.wiki.git" "$WIKI_TMP/wiki"; then
  rsync -a --delete --exclude README.md --exclude .git/ "$WIKI_TMP/wiki/" "$WIKI_DIR/"
  cat > "$WIKI_DIR/README.md" <<EOF
# GitHub Wiki mirror

Repository: https://github.com/$REPOSITORY/wiki

This directory is generated by \`scripts/sync-github-context.sh\`.
Edit the Wiki on GitHub, then run the script to refresh this mirror.
EOF
else
  echo "Wiki is disabled, empty, or unavailable; keeping the existing local mirror." >&2
fi

echo "GitHub context mirror updated. Review and commit changes normally."
